#! /usr//bin/env bash

usage(){
cat << EOF
usage: $0 options

Utility to record rtsp stream locally with vlc (tested with v2.2.1). It also deletes recordings older than 7 days

USAGE: ./start_rtsp_recording -c 127.0.0.1 -s ~/history -d 3600 -r 7'
Required arguments: 
  -c 	camera 		- rtsp://127.0.0.1:0000/stream'	RTSP_SOURCE
  -s 	storage 	/../.. 			directory WITHOUT TRAIING SLASH to record into
  -d 	clip-duration 	3600 			clip duration in secs
  -r    retention	7			days to keep the records for, after which they are removed.

OPTIONS:
   -h 	Show this message
EOF
}

DATE_TAKEN=$(date +\%Y-\%m-\%d_\%Hh\%Mm\%Ss)
FILE_PREFIX='record'
RESOURCE=
STORAGE=~/history
DURATION=3600
RETENTION=7

# OSX. Feel free to modify.
VLC_LOCATION=/Applications/VLC.app/Contents/MacOS/VLC

while getopts “hc:s:d:r:” OPTION
do
    case $OPTION in
         h)
             usage
             exit 1
             ;;
         c)
             RESOURCE=$OPTARG
             ;;
         s)
             STORAGE=$OPTARG
             ;;
         d)
             DURATION=$OPTARG
             ;;
         r)
             RETENTION=$OPTARG
             ;;
         \?)
             usage
             exit
             ;;
    esac
done

# ----------------------------------------------------------------------
# delete files from the directory which are older than 7 days (local storage)
# ----------------------------------------------------------------------

#echo "find $STORAGE/$file_prefix-* -mmin +$RETENTION -exec rm {} \;"
#    mtime +7  - for any files older than (days)
#    mmin +900 - for any files older than (minutes)

find $STORAGE/$FILE_PREFIX-* -mtime +$RETENTION -exec rm {} \;



# ----------------------------------------------------------------------
# start recording
# ----------------------------------------------------------------------

$VLC_LOCATION -I dummy $RESOURCE --sout file/ts:$STORAGE/$FILE_PREFIX-$DATE_TAKEN.ts --run-time=$DURATION --stop-time=$DURATION vlc://quit

